### ISSUE TITLE
Настройка рабочего окружения

### ISSUE THREAD

**Issue by Feodorov** [zmactep/ig-pipeline#10]
1) Настроить VPN - нужен доступ к тестовому серверу, файловому серверу и к SQL базе.
2) Поставить на тестовую машину MySQL - я займусь подключением наших тулов к базе

**Comment by zmactep** [comment]
FTP, MySQL подняты. Есть доступ из локальной сети.
SSH доступен повсеместно.

В ближайшее время пробросят нужные порты, но уже можно работать.

**Comment by Feodorov** [comment]
Паша крутой! Спасибо.
