### ISSUE TITLE
Рефакторинг

### ISSUE THREAD

**Issue by Feodorov** [zmactep/ig-pipeline#11]
Пришли к следующей структуре каталогов:
- ig-backend
- ig-frontend
- data
- tools

tools:
- ig-splitter (./ngs-splitter && ./splitter)
- ig-snooper (./svm_data_generator and scripts)
- ig-aligner (./gene_*)
- ig-container
- common_lib

Аналогично структуре папки tools будем создавать приложения в ig-frontend.

**Comment by zmactep** [comment]
Я займусь рефаторингом/переводом на Scala ig-container и просмотрю snooper подробнее. Посмотри трезвым взглядом на ig-aligner. пожалуйста. Там явно есть что сделать с юзабилити помимо изменения вывода.

Плюс завтра будет ревью передницы.
