### ISSUE TITLE
Относительные пути

### ISSUE THREAD

**Issue by zmactep** [zmactep/ig-pipeline#14]
Сейчас много где используются абсолютные пути для гермлайнов, регионов и прочего. Наверное, пора переделать их на относительные.

**Comment by Feodorov** [comment]
На самом деле это дубликат Issue #16 - Storage app в ig-frontend хранит отображение метки (="относительный путь") на абсолютный путь. Или я не прав?

**Comment by zmactep** [comment]
Нет, тут еще вопрос в том, чтоб из всех тулов убрать /User/Kos .. и оставить только относительные пути

**Comment by Feodorov** [comment]
1. С тебя список тулов и мест где это встречается. Кажется, остались только gene_*
2. Например, если заменить абсолютный путь к домашней директории в ig-backend в application.conf на ~ он перестает работать. Абсолютные пути из конфигов никуда не денутся, а будут заменены на /usr/local и подобные, как в ig-config.

**Comment by zmactep** [comment]
Договоренность о хранении репозитория в /opt для унификации путей у разработчиков.

Можно установить symlinks из того места, где реально лежит репозиторий.
