### ISSUE TITLE
Кластеризация по регионам

### ISSUE THREAD

**Issue by zmactep** [zmactep/ig-pipeline#17]
- Получение fasta и файла разметки
- Выделение нужного региона
- Возврат дерева кластеризации по данному региону, множественного выравнивания, fasta-файлов кластеров

**Comment by Feodorov** [comment]
Это таск для тебя? Тул для кластеризации у тебя есть?

**Comment by zmactep** [comment]
Да, да.

**Comment by zmactep** [comment]
C учетом наличия скрипта вытаскивания регионов, закрыто.
