### ISSUE TITLE
Выгрузка данных с сервера

### ISSUE THREAD

**Issue by zmactep** [zmactep/ig-pipeline#18]
Возможность архивации и сохранения указанных данных.

**Comment by Feodorov** [comment]
Совсем не понятно что за данные и куда выгружать? Ты про результаты выравнивания/поиска регионов? Или про исходные fasta/kabat? 
Если про первые - то их не нужно хранить, а нужно просто добавить кнопку "скачать результат одним архивом". 
Если про вторые - то, кажется, это просто загрузка по FTP на сервер, тут можно найти какой-нибудь сторонний понятный клиент, или FTP с вебмордой. Мне кажется, не стоит делать кнопку "Upload" в ig-frontend, чтобы не гонять через него гигабайтные файлы.

**Comment by zmactep** [comment]
Результаты выравнивания, так что можно и не хранить, а генерировать на лету.

**Comment by Feodorov** [comment]
Не понял тебя. Что в итоге должно быть выполнено в этом таске? Результаты не храним, модели и данные выгружаются через сторонний FTP клиент.

**Comment by zmactep** [comment]
В случае регионов выгружаем файл разметки в человеко-читаемом виде.

**Comment by Feodorov** [comment]
Опять никакой конкретики. Выгружаем result_pic.txt (который я отрисовываю в интерфейсе)? Или какой-то другой файл разметки? Что ты понимаешь под "выгружаем"? Кнопка "Сохранить как"? Или зайти через FTP и скопировать (в этом случае в таске совсем нечего делать)? 

Меньше конкретики - дольше делается Issue. Примета такая :)

**Comment by zmactep** [comment]
Итак,
1. result_pic.txt отображаем в интерфейсе
2. Предоставляем возможность скачать result_pic.txt (кнопка "Сохранить как")

Вообще, смысл таска в подготовке механизма сохранения фалов вообще.
У каждого пользователя есть набор файлов, к которым у него есть доступ. Нужен механизм их передачи на кнопку "Сохранить как". А какие именно файлы - это потом определяется.

**Comment by Feodorov** [comment]
1. В /storage/ добавляется отдельное поле "user" или "group"
2. Там же добавляется фильтрация вывода файлов по имени пользователя
3. И добавляется кнопка "Download"

Все.
Кнопку Download прикручу сегодня.

А вообще, если у тебя в голове есть схема, как реализовать этот механизм - нарисуй ее или запиши. Потому что мне сложно догадаться по изначальной задаче "Возможность архивации и сохранения указанных данных" что требуется на самом деле, а делать что-нибудь, что ты потом забракуешь и что пойдет в мусорное ведро - я не хочу.

**Comment by zmactep** [comment]
Мы просто с тобой это обсуждали лично, и я добавлял issues на уровне mindmap, дабы вспомнить, о чем речь шла. Ок, буду конкретизировать.

**Comment by Feodorov** [comment]
Да, все нужно записывать, чтобы не было разночтений.
