### ISSUE TITLE
Вырезание региона

### ISSUE THREAD

**Issue by zmactep** [zmactep/ig-pipeline#19]
С божью (ig-tools/ig-snooper/ig_snooper_utils) помощью получать отдельный FASTA файл с указанным регионом из каждого сиквенса входного FASTA + Kabat файлов.

**Comment by Feodorov** [comment]
Пример запуска:

```
python cut_region.py --input=/Users/Kos/Dropbox/Biocad/ig-pipeline/data/train/VDJH_train.fasta --kabat=/Users/Kos/Dropbox/Biocad/ig-pipeline/data/train/VDJH_train.kabat --output=/Users/Kos/Downloads/output.fasta --reg_num=6
```

Номер региона начинается с 0. Если сиквенса нет в kabat, или номер региона выходит за границу - в консоль выводится сообщение, а сиквенс игнорируется.
