### ISSUE TITLE
Перенести все либы из gene_* в common_lib

### ISSUE THREAD

**Issue by Feodorov** [zmactep/ig-pipeline#3]

**Comment by zmactep** [comment]
Перенес reverse_complement в utils, таким образом полностью почистил комбинатор от дубликатов: он теперь использует common_lib.

Commit e0462422656776464f7d74e3ca183a2531755c3a

Я могу доделать этот issue полностью, поскольку, наверное, это надо сделать раньше, чем #12

**Comment by Feodorov** [comment]
OK, забирай.
