### ISSUE TITLE
Перенос scan_dir.py

### ISSUE THREAD

**Issue by zmactep** [zmactep/ig-pipeline#30]
Перенести скрипт scan_dir.py из снупера в какое-нибудь логичное место (не в ig-tools), переписать путь в backend.

**Comment by Feodorov** [comment]
А почему не в ig-tools? Предлагаю вынести scan_dir.py, cut_region.py, split_fasta_to_learn_and_train_datasets и compare_kabat.py из ig_snooper_utils в отдельную папку ig-utils в корне ig-tools. Создадим два модуля - utils (туда пойде scan_dir.py), и bio - туда пойдут оставшиеся. Все эти скрипты general purpose, и могут пригодится не только снуперу.

**Comment by zmactep** [comment]
Здраво, одобряю.
