### ISSUE TITLE
Форма кластеризации

### ISSUE THREAD

**Issue by zmactep** [zmactep/ig-pipeline#31]
В форме кластеризации SIM и SHORTEST CONS - это флаги без значений, соответственно, выглядить они должны checkbox`ами.

Проверить, что подобные булевые флаги правильно генерятся в строке команды в backend.

**Comment by zmactep** [comment]
$ ls -R
.:
_alignment.fasta_
clusters
cluster_tree.dnd - этот тоже подчеркнут
_consensus.fasta_
dendogram.png
heavy_reg.fa
output.txt

./clusters:
NoneG1.fasta
NoneG2.fasta
NoneG3.fasta
NoneG4.fasta
NoneG5.fasta

**Comment by Feodorov** [comment]
Сделал. Посмотри Issue #32 - там есть скриншоты и логи.
