### ISSUE TITLE
Баги frontend 18.11

### ISSUE THREAD

**Issue by zmactep** [zmactep/ig-pipeline#33]
1. ~~Неправильно формируется строка запуска standalone train~~ Решили. Проблема была в использовании не последней версии Train, которая выдавала ошибку из-за отсутствующего параметра.
2. ~~Проверка уникальности файла в storage идет только по ID, а не по тройке (группа-ран-id)~~ Поправил

**Comment by zmactep** [comment]
1. Добавление директорий в storage (например, для make_report) в добавлении файла (file tree)
2. Множественный выбор файлов в file tree
3. ~~Добавление директории в список файлов при автоматическом добавлении результатов работы тула в storage~~ Поправил scan_dir.py - теперь добавляются и директории. Все директории должны заканчиваться на / чтобы я выводил их в списках директорий.

**Comment by Feodorov** [comment]
Теперь по клику на папку добавляется сама папка, и все ее содержимое (нерекурсивно). К сожалению, малой кровью множественный выбор файлов (как с зажатым CTRL) сделать не получится. Пусть будет добавление всей папки
