### ISSUE TITLE
Создать backend на java

### ISSUE THREAD

**Issue by Feodorov** [zmactep/ig-pipeline#6]
Выбрали java, так как мы все знаем ее на достаточном для быстрой разработки уровне. Протокол - JSON. Описание - в protocol.json

**Comment by superbobry** [comment]
Быстрая разработка на Java это оксюморон :)

**Comment by Feodorov** [comment]
Обоснуй?

**Comment by superbobry** [comment]
Имею опыт разработки на жаве и на питоне.

**Comment by Feodorov** [comment]
Я думал, у тебя есть что-то конкретное.
На джаве, например, есть maven. Что-бы использовать множество библиотек, я просто добавляю описание в pom.xml, и система сама прокачает их на _любой_ машине и задействует в проекте. Ничего не нужно делать. Контр-пример: в скриптах на питоне я использую biopython, и вынужден ручками ставить его на каждой машине (кстати, а можно иначе)?
В общем, приводи примеры, мне будет полезно узнать новое про питон и почему он крутой :)

**Comment by superbobry** [comment]
Для питона есть [`pip`](http://www.pip-installer.org/en/latest), который делает ровно то же, что и maven. Пример:

``` bash
$ cat requirement.txt
BioPython==1.62
$ pip install -r requirements.txt
...
```

Чтобы разные версии пакетов не кофликтовали, для каждого проекта заводят [виртуальное окружение](http://www.virtualenv.org/en/latest). Можно [завести](http://virtualenvwrapper.readthedocs.org/en/latest/) пачку виртуальных окружений и реюзать их между проектами. Например:

``` bash
$ mkvirtualenv bio-env
New python executable in bio-env/bin/python
Installing setuptools............done.
Installing pip...............done.
$ workon bio-env 
$ pip install yada-yada  # ставит пакет в окружение bio-env
$ deactive
```

Чтобы получить все эти чудеса на маке достаточно сделать:

``` bash
$ sudo easy_install pip virtualenv virtualenvwrapper
$ echo "source /usr/local/bin/virtualenvwrapper_lazy.sh" >> .bashrc
```

**Comment by superbobry** [comment]
Насколько я понимаю, вы с Пашей задумали писать некоторый сервис, выполняющий задания из вебни на Django. В питоне такое поведение легко поиметь заюзав [Celery](http://celeryproject.org). Это обертка над разными message queues для асинхронного выполнения задач. Вы нахаляву получаете интеграцию с питонокодом, распределенность -- работники (workers) могут находиться на разных нодах и мониторинг статуса задач. Что ещё надо?

**Comment by zmactep** [comment]
Мне нравится. Т.е. вся идея именно разнести вебню и алгоритмы как можно дальше друг от друга, поставив между ними некоторый сервис. Проблема встала именно с выбором языка этого сервиса. Ну, и тут встала Java. Вообще, если удастся убедить Костю, то я всецело за Питон в написании этого сервиса, т.к. он мне кажется проще и удобнее для разработки. Но тут проблема, как я понял, что Костя не очень уверен в своих питоновых силах.

**Comment by zmactep** [comment]
Короче, начнем, а там видно будет. Пока еще большая беда с frontend, т.к. это никто из нас писать просто не умеет.. )

**Comment by Feodorov** [comment]
http://akka.io/ - обмен сообщениям, высокая производительность, распределенность, воркеры и т.д. и т.п. на Java. А зачем нам интегрированность с питонокодом? У нас шелл-скрипты, которые запускают сборную солянку из разных тулов.
Можно и питон, но на нем я буду писать долго и плохо. Если вы готовы это терпеть, до давайте выберем питон :)

**Comment by Feodorov** [comment]
Тут просто такая засада:
Как я вижу разработку мною бэкэнда на Java: пришел, сконфигурил maven, выкачал jetty, добавил org.json, и запустил сервак который слушает сообщения. Через пару дней у нас уже работающий скелет сервера.
Как я вижу разработку на питоне: пришел, запустил IDE, загрустил, понял что я не знаю с чего начать ибо не знаю ни одной либы или фреймворка. Закрыл IDE, расстроился и лег спать :) Через пару дней у нас уже неработающий говнокод на питоне :) Need help, короче. Было бы круто, если бы кто-нибудь тогда сконфигурировали минимальный проект и сделал простенький скелет.

**Comment by superbobry** [comment]
Вброс: ну слушай, akka как я понимаю, это такой эрланг для тех кто не осилил синтаксис пролога.

А по сути: ну пиши на жаве, я ничего полезного на жаве не писал, только всякие околонаучные штуки. По результатам: на питоне писать сильно удобней.

**Comment by zmactep** [comment]
Ок, давайте начнем с Java. Тем более, если есть какой-то опыт. Но я сегодня на Питоне написал заглушку сервера за 5 минут и 20 строк кода, используя только стандартную библиотеку. Так что я верю, что если что-то не заладится, мы сможем быстро мигрировать.

**Comment by zmactep** [comment]
```
import socketserver

class MyTCPHandler(socketserver.BaseRequestHandler):

    def handle(self):
        data = self.request.recv(1024).strip()
        to_send = SOME_MAGIC(data)
        self.request.send(to_send)

if __name__ == "__main__":
    HOST, PORT = "localhost", 9999

    server = socketserver.TCPServer((HOST, PORT), MyTCPHandler)
    server.serve_forever()
```

Чисто для справки.

**Comment by superbobry** [comment]
А есть ещё [`gevent`](http://www.gevent.org/), который через костыль в CPython делает кооперативную многозадачность. В частности, все IO операции неявно отдают управление другим зелёным потокам.

**Comment by Feodorov** [comment]
А вот и скелет сервера, в ig-backend. Команды, пока что, он не разбирает, а просто запускает скрипт. Нужно будет доделать скрипт так, чтобы можно было запускать несколько экземпляров параллельно.

**Comment by Feodorov** [comment]
Добавил поддержку протокола команд. С текущими настройками сервер слушает порты 8080 (HTTP) и 9999  (TCP). Примеры команд в README.md. В src/main/resources/application.conf  нужно прописать пути к существующим директориями для хранения моделей и для работы воркеров.
