### ISSUE TITLE
Отрисовка результатов поиска регионов в интерфейсе

### ISSUE THREAD

**Issue by Feodorov** [zmactep/ig-pipeline#9]
Паша, нужны примеры визуализации данных, чтобы понять куда двигаться.

**Comment by zmactep** [comment]
Я думаю, что мы можем ориентироваться на IMGT/V-QUEST

Т.е. для начала просто писать сиквенсы в виде

<----FR1--->    <---CDR1--> .......
AAAAAAAAA    BBBBBBBBB .......

**Comment by Feodorov** [comment]
Появилось в 0b3ac3119a
Отрисовку в интерфейсе пока делать не стал, так как нужно понять, как отрисовывать большие файлы. Возможно, нужна просто ссылка на файл.

Теперь ./predict.sh создает файл results_pic.txt со следующим содержимым:

IGKV6D-41_01_IGKJ3_01{2}
GATGTTGTGATGACACAGTCTCCAGCTTTCCTCTCTGTGACTCCAGGGGAGAAAGTCACCATCACCTGCCAGGCCAGTGAAGGCATTGGCAACTACTTATACTGGTACCAGCAGAAACCAGATCAAGCCCCAAAGCTCCTCATCAAGTATGCTTCCCAGTCCATCTCAGGGGTCCCCTCGAGGTTCAGTGGCAGTGGATCTGGGACAGATTTCACCTTTACCATCAGTAGCCTGGAAGCTGAAGATGCTGCAACATATTACTGTCAGCAGGGCAATAAGCACCCTCATCACTTTCGGCCCTGGGACCAAAGTGGATATCAAAC
<--------------------------------FR1--------------------------------><-------------CDR1--------------><--------------------FR2--------------------><-------CDR2--------><---------------------------------------------FR3----------------------------------------------><---------------CDR3----------------><--------FR4--------->
IGKV6D-41_01_IGKJ4_01{0}
GATGTTGTGATGACACAGTCTCCAGCTTTCCTCTCTGTGACTCCAGGGGAGAAAGTCACCATCACCTGCCAGGCCAGTGAAGGCATTGGCAACTACTTATACTGGTACCAGCAGAAACCAGATCAAGCCCCAAAGCTCCTCATCAAGTATGCTTCCCAGTCCATCTCAGGGGTCCCCTCGAGGTTCAGTGGCAGTGGATCTGGGACAGATTTCACCTTTACCATCAGTAGCCTGGAAGCTGAAGATGCTGCAACATATTACTGTCAGCAGGGCAATAAGCACCCTCAGCTCACTTTCGGCGGAGGGACCAAGGTGGAGATCAAAC
<--------------------------------FR1--------------------------------><-------------CDR1--------------><--------------------FR2--------------------><-------CDR2--------><---------------------------------------------FR3----------------------------------------------><----------------CDR3-----------------><--------FR4--------->

**Comment by Feodorov** [comment]
Сделал вывод в браузере. 
localhost:8000/listing/?file=/Users/Kos/Downloads/results_pic.txt
Ссылка будет доступна со страницы результатов, в последней колонке ('Response')
